sudo: required

services:
  - docker

language: go

go:
    - "1.14"

env:
    - GO111MODULE=on

before_script:
    - env
    - docker version
    - chmod 777 ./build_image.sh && ./build_image.sh

script:
    - chmod 777 ./push_image.sh && ./push_image.sh
